name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
  
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: test
      run: ./main.out
  
  clean:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: clean
      run: make clean