name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: executing tests
      run: ./main.out
    - name: installing valgrind
      run: sudo apt install -y valgrind
    - name: check leaks
      run: |
          valgrind -q --leak-check=full --suppressions=t.supp --error-exitcode=10 ./main.out
