name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: installing valgrind
      run: sudo apt install -y valgrind
    - name: check leaks
      run: |
          valgrind -v --leak-check=full --error-exitcode=2 ./main.out 2> dump.log
          cat dump.log
